repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings,
                                  flake8-import-order, flake8-mutable,
                                  flake8-pep3101]
-   repo: https://github.com/jsh9/pydoclint
    rev: 0.6.5
    hooks:
    -   id: pydoclint
        args: [--style=sphinx, --check-return-types=False]
